var data_name = {
	"name_warn": "请填写考生姓名与本人证件一致",
	"idcode_warn": "请填写考生本人身份证号或护照号",
	"email_warn": "用于登陆、收取通知",
	"tel_warn": "请填写考生本人联系电话",
	"register_warn": "请填写考生临时登记编号",
	"major_warn": "请填写考生所学专业",
	//"job_history_start_time": "开始时间",
	//"job_history_end_time": "结束时间",
	"job_history_company": "工作单位名称",
	"job_history_duty": "职务/岗位",
	"job_history_start_time_warn": "工作的开始时间",
	"job_history_end_time_warn": "工作的结束时间",
	"job_history_company_warn": "请填写工作履历的公司名称",
	"job_history_duty_warn": "请填写工作履历的职务",
	"present_work_unit_warn": "现工作单位",
    //"project_history_start_time": "开始时间",
	//"project_history_end_time": "结束时间",
	"project_history_project_name": "项目名称",
	"project_history_amount": "合同金额(万元)",
	"project_history_money": "软件和信息技术服务费用比例(%)",

	"project_history_start_time_warn": "曾负责或参与项目的开始时间",
	"project_history_end_time_warn": "曾负责或参与项目的结束时间",
	"project_history_project_name_warn": "系统名称请严格按照系统集成项目合同填报",
	"project_history_amount_warn": "合同金额",
	"project_history_money_warn": "项目合同中软件开发费、咨询设计费、集成实施费和运营维护费合计所占合同金额的比例",

	"detail_project_name_warn": "系统名称请严格按照系统集成项目合同填报",
	"detail_project_start_time_warn": "项目的开始时间",
	"detail_project_end_time_warn": "项目的结束时间",
	"detail_industry_warn": "项目的所属行业",
	"detail_scale_warn": "以项目完成量人月统计",
	"detail_amount_warn":"按照合同填写",
	"detail_money_per_warn": "填写项目合同中软件开发费、咨询设计费、集成实施费和运营维护费合计所占合同金额的比例",
	"detail_plan_duraion_warn": "项目计划工期按月填写",
	"detail_actual_duraion_warn": "项目实际完成工期按月填写",
	"detail_project_background_warn": "项目背景",
	"detail_project_background_text_warn": "项目发起的原因/项目的机遇与优势/项目的挑战与劣势",
	"detail_project_goal_warn": "项目目标",
	"detail_project_goal_text_warn": "包含质量目标，工期目标、费用目标和交付产品特征与特征的主要描述",
	"detail_role_warn": "项目中担任的角色",
	"detail_main_work_warn": "主要工作",
	//"detail_right_scope_warn": "",
	//"detail_budget_warn": "",
	//"detail_group_type_warn": "",
//	"detail_office_warn": "",

	//"detail_solution_type_warn": "",
//	"detail_solution_detail_warn": "",
//	"detail_solution_detail_warn": "",

//	"detail_promote_warn": ""
}