var student_data = {
    "title": "",
    "exam_code": "",
    "photo":"",
    "name": "",
    "id_type": "",
    "idcode": "",
    "email": "",
    "tel": "",
    "education": "",
    "register":"",
    "major":"",
    "exam":"",
    "work_life": "",
    "job_history": [],
    "present_work_unit": "",
    "project_history": [],
    "detail": {
        "project_name": "",
        "project_start_time": "",
        "project_end_time": "",
        "industry": "",
        "scale": "",
        "amount": "",
        "money_per":"",
        "plan_duraion": "",
        "actual_duraion": "",
        "project_background": "",
        "project_goal": "",
        "role": "",
        "main_work": "",
        "right_scope": "",
        "budget": "",
        "group_type": "",
        "office": "",
        "solution": [],
        "summary":"",
        "promote": "",
        "detail_problem":""
    }
};
var is_indentity={
		"identity_type":"",
		"nationality":""
	}